### ISSUE TITLE
.addModule from a CDN

### ISSUE THREAD

**Issue by bebjakub** [liferay/liferay-amd-loader#101]
Hello,
I would like to add external isotope.js to my theme generated by liferay-theme-generator.

src/main.js
`AUI().ready(
  function() {
    Loader.addModule({
    dependencies: [],
    exports: '_',
    name: 'isotope',
    path: 'https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.2/isotope.pkgd.js'
	});
  }
);`
But its not working ofcourse :) Is possible add external libraries?

**Comment by jbalsas** [comment]
hey @bebjakub, have you tried setting `fullPath` instead?

**Comment by bebjakub** [comment]
no :) but I achieve it with:
src/main.js
`(function() {	
	require(
		'https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.2/isotope.pkgd.min.js',
		function(isotope) {
			$('.grid').isotope({
			// options
			itemSelector: '.grid-item',
			layoutMode: 'fitRows'
			});
		}
		
	);
})();`
