### ISSUE TITLE
Replace jshint with eslint

### ISSUE THREAD

**Issue by ipeychev** [liferay/liferay-amd-loader#115]
We have to replace the jshint with eslint which provides more flexibility

**Comment by jbalsas** [comment]
Hey @ipeychev, I'm working with @eduardolundgren on a general proposal around formatting and guidelines. This includes, among others, `prettier` and a default `eslint` config.

**Comment by jbalsas** [comment]
You are way too fast 😂 

I think the one here is very close to what we were discussing... see https://github.com/eduardolundgren/eslint-config-liferay

**Comment by ipeychev** [comment]
Very good, Chema, please notify me when ready :)
