### ISSUE TITLE
Follow source formatting guidelines

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-amd-loader#121]
We're starting to come around [prettier](https://github.com/prettier/prettier) for source formatting all of our projects.

The standard settings are probably going to be:

Setting | Value | Description
--- | --- | ---
printWidth | 80 | Fit code within this line limit
useTabs | true | Indent lines with tabs
tabWidth | 4 | Number of spaces per tab
singleQuote | true | Use single quotes
trailingComma | all | Adds trailing commas wherever possible (function arguments). See [tc39 proposal](https://github.com/tc39/proposal-trailing-function-commas)
bracketSpacing | true | Controls the printing of spaces inside object literals
jsxBracketSameLine | false |
parser | ‘babylon’ | Which parser to use. 
semi | true | Whether to add a semicolon at the end of every line

The only one we might need to change here is `trailingComma`, since that might break things for us right now, I guess, unless we move to ES7 and transpile...

**Comment by yuchi** [comment]
You are going to be pissed off by inlined `else` and `else if`. Great choice anyway!!

**Comment by ipeychev** [comment]
We may transpile this time and not change anything, yeah :)
This project relies on dealing with `arguments` and in 2014/2015 transpilers weren't doing great job from performance point of view with them (causing bailout in V8, AFAIR). That was the main reason to write old school JS. But it is 2017, so I vote for transpiling this time, using const, let, maybe rest parameters and so on :)

**Comment by izaera** [comment]
I have sent a PR to format sources with prettier but it is not transpiling. 

Given the complexity of the build process, IMHO creating a task for transpiling is not worth the effort yet unless we are going to start using ES2015 in this project. But feel free to correct me if any of you think we need it. In that case, I can add it to this PR or we can create another issue.
