### ISSUE TITLE
Make maps resolution repeatable and less surprising

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-amd-loader#124]
After the introduction of #117 it is not clear how a set of mappings will behave when there are duplicate parts. 

Let's see an example, given this configuration:

```javascript
__CONFIG__.maps = {
            'aaa': 'zzz',
            'aaa/bbb': {
                value: 'yyy',
                exactMatch: true
            }
}
```

What happens if I do:

```javascript
require('aaa/bbb')
```

Right now the algorithm is applying the mappings in a non-deterministic order with a `for(in)` loop and the search stops after the first hit, thus it's impossible to know if the first mapping will be applied giving `zzz/bbb` as result or if the second map will win and we will get `yyy` as a result.

So, to follow the spirit of the previous maps feature that firstly applied specific maps and then resorted to `*`, I propose to apply mappings in this order:

1. exactMatch maps
2. non-exactMatch maps
3. the `*` map

This way the algorithm is deterministic again and follows the least surprise principle, as it proceeds searching from the more specific to the more general.

**Comment by ipeychev** [comment]
Yeah, that makes sense.
