### ISSUE TITLE
Don't load old jquery plugins

### ISSUE THREAD

**Issue by mfd** [liferay/liferay-amd-loader#149]
Hi! 
my env: Liferay 7 GA4
my modules is $.fn is load, but my init code in my theme (main.js) not work

```config.js
//config.js
define('jquery', function () {
  return window.jQuery;
});

Loader.addModule({
    dependencies: ['jquery'],
    anonymous: true,
    name: 'owlCarousel',
    //exports: 'jquery.owlCarousel',
    fullPath: 'https://unpkg.com/owl.carousel@2.2.0/dist/owl.carousel.js'
});

Loader.addModule({
    dependencies: ['jquery'],
    anonymous: true,
    name: 'prettyPhoto',
    exports: 'jquery.prettyPhoto',
    fullPath: 'https://cdnjs.cloudflare.com/ajax/libs/prettyPhoto/3.1.6/js/jquery.prettyPhoto.min.js'
});
```

```js
// theme/src/js/main.js

  require(['prettyPhoto','owlCarousel'], function(prettyPhoto, owlCarousel) {
    console.log(jQuery.fn.prettyPhoto);
    console.log(jQuery.fn.owlCarousel);
  });


(function() {
  'use strict';
    $(document).ready(function() {
        $("a[class^='prettyPhoto']").prettyPhoto({});
        $("#our-customers").owlCarousel({
            slideSpeed:10,
            items: 5
         });
        console.log(jQuery.fn.prettyPhoto);
        console.log(jQuery.fn.owlCarousel);

    });
})();




```

**Comment by izaera** [comment]
Hi @mfd:

What's the exact problem you are facing? What do you mean by not loading? 

Are you getting any error in the Javascript console? 
Or is require call failing? 
Or is jQuery.fn missing in `theme/src/js/main.js`?

Also, how do you guarantee that jquery is already loaded and put in the window object when the `theme/src/js/main.js` code is run? How are you loading jQuery?

**Comment by jbalsas** [comment]
Hey @mfd, please take a look at the [Using External Libraries tutorial](https://dev.liferay.com/develop/tutorials/-/knowledge_base/7-0/using-external-libraries), specially at the note about hiding the loader:

> Note: With the release of Liferay Portal CE 7.0 GA4 and Liferay Digital Enterprise 7.0 SP2 (Fix Pack 8), it will be possible to hide the Liferay AMD Loader through Liferay Portal’s System Settings. Open the Control Panel, navigate to Configuration → System Settings, and click JavaScript Loader under the Foundation tab. Finally, uncheck the expose global option.
