### ISSUE TITLE
Lazy require function

### ISSUE THREAD

**Issue by Robert-Frampton** [liferay/liferay-amd-loader#157]
Currently in liferay-portal, we have a utility called `Liferay.provide` which creates a function 
that can be called synchronously, but only loads the necessary YUI modules when the function is first invoked. 
This allows for easily creating global utilities that leverage async code without preloading any of the dependencies.

For example.

```javascript
Liferay.provide(
	Util, 
	'someMethod', 
	function(foo) {
		new A.SomeWidget(foo);
	},
	['some-widget']
);

Util.someMethod('foo');
```

I propose that we provide a similar, but also simpler functionality for the amd loader.

```javascript
Util.someMethod = Loader.lazy(
	'some-module',
	function(someModule, foo) {
		someModule(foo);
	}
);

Util.someMethod('foo');
```

**Comment by izaera** [comment]
Shouldn't this issue be closed @Robert-Frampton ? @jbalsas told me that you sent it to the portal...
