### ISSUE TITLE
Liferay 7 DXP fixpack 37: define() and require() are missing

### ISSUE THREAD

**Issue by caneta** [liferay/liferay-amd-loader#162]
With fixpack 37, global functions `define()` and `require()` are not available anymore.

This breaks a lot of JavaScript inside a custom theme, especially if you have included some third party plugin AMD compatible: they search for those global functions indeed...
Why this breaking change?

I've noticed that Liferay AMD Loader upgrades from version 2.1.0 to 2.3.0, passing from fixpack 36 to 37...is this change related to Loader version?

[Here a related thread](https://web.liferay.com/community/forums/-/message_boards/message/103474658) on Liferay Forum.

**Comment by TBurk83** [comment]
Same issue here. Not good.

**Comment by yuchi** [comment]
This is not probably an issue with the AMD Loader itself, but rather with its configuration.

Starting initial 2017 there has been a configurable option on DXP to have the global define/require available or not. If enabled (which _was_ by default) it would bring the namespace `Liferay.Loader.require` and `Liferay.Loader.define` in the “global namespace” (a.k.a. `window`).

They indeed changed the default recently: https://github.com/liferay/liferay-portal/commit/d6122d10f031ad987afe5bfbbb7e23cc964323e8

You can configure it back to exposing the global define/require by going in _Control Panel › System Settings_ and searching for «Loader».

**But** this is not a good idea at all! That default change was made to simplify workflows that uses external libraries.

**Comment by jbalsas** [comment]
Hey guys, sorry about this.

As @yuchi pointed out, we added the setting a while back to simplify workflows using 3rd party libraries in a different way. We kept it enabled by default so we didn't break existing code.

This change was made in preparation for `7.1` and should have never been backported to `7.0`. I'm not sure how that happened, so we'll investigate and revert it as soon as possible.

In the meantime, you can indeed change the configuration to make sure that the loader methods are exposed once again.

/cc @antonio-ortega

**Comment by caneta** [comment]
Thank you @yuchi  and @jbalsas.
At firts, I'm forced to change the default because this change broke several production environments.
Next I have to see how to change my code in order to use the new and preferable configuration.

**Comment by izaera** [comment]
@caneta We have a babel plugin that we use to namespace `define` and `require` calls when running code through the `liferay-npm-bundler`. It is published in npmjs, so it may be of help to you, perhaps.

It is here: https://github.com/liferay/liferay-npm-build-tools/tree/master/packages/babel-plugin-namespace-amd-define

Maybe you can set it up so that your projects use it to convert all `require` calls to `Liferay.Loader.require`.

If you need help I can assist you.

**Comment by caneta** [comment]
@izaera,  that was exactly the problem I was worried about, thank you so much for your suggestion!

**Comment by caneta** [comment]
Ok, I'm trying to make things work with the new approach.
My context is a custom Liferay theme, not a portlet: I set up an hook running babel inside my gulpfile.

Using the babel plugin @izaera  suggested works fine, but only for my custom JavaScript modules.
What about third party modules, let's say [enquire.js](https://github.com/WickyNilliams/enquire.js/)?
I were used to include it with a simple `import enquire from 'enquire.min';` and that does not work anymore because that plugin searches for a global definition of `define()`.

My question is: is there a way to make things work using one of the submodules for the `liferay-npm-bundler` [listed here](https://github.com/liferay/liferay-npm-build-tools/tree/master/packages), adding it to my custom theme? Or may I have to wrap that library inside a `Liferay.Loader.define()` definition?

**Comment by jbalsas** [comment]
Hey @caneta, the proper fix for you is to just enable the setting preference back. That would get everything back to normal.

If you know what you’re doing (and I know you do), then it’s totally fine to expose the loader. The problem comes when the implications of having and amd loader are not clearly understood(again, not your case). As we’ve identified the latter to be the most common case, we’re flipping the default for 7.1. If you upgrade, the solution would the same, just turn the setting that exposes the loader back on.

We’ll revert this in 7.0 as it should’ve never made it in. Hope we can get it in for the next FP, although I recognize the damage is already done :(

**Comment by caneta** [comment]
Ok @jbalsas, got it. For production environments you are right.

But I'm curious if this situation is solvable inside a theme with `Liferay.Loader` namespace as default: I think this will be useful to me very soon! 😄

**Comment by izaera** [comment]
@caneta just for the sake of clearing your doubt, it could be possible to use `liferay-npm-bundler` with no plugins and configuring babel (inside the liferay-npm-bundler run) with the plugin I proposed. It is not a supported configuration but should work as liferay-npm-bundler would run babel plus the plugin through all your third party modules. However, it wouldn't work for `import` as the babel plugin just namespaces `require` and `define`. That is, you would need to run it through transpiled code.

Said that, it's probably better to do what @jbalsas proposes :-D

**Comment by caneta** [comment]
Maybe not the best solution ever, but I made my theme work with the new configuration.
Here an explanation of what I did: advices and comments are really welcome!

Problem: I want to set up in my Liferay 7 custom theme, 3 JavaScript plugins:

1. [bootstrap-select](https://github.com/silviomoreto/bootstrap-select): amd compliant, anonymous module, jquery dependent
2. [bootstrap-validator](https://github.com/1000hz/bootstrap-validator): amd not compliant, jquery dependent
3. [enquire.js](https://github.com/WickyNilliams/enquire.js/): amd compliant, anonymous module, no dependencies

To modify plugin sources, I make a copy of them inside a `src/js/plugins` directory, through a simple tool named [frontend-dependencies](https://github.com/msurdi/frontend-dependencies).

My **package.json** looks like the following (omitting not interesting parts):
```
{
  "name": "my-theme",
  "version": "1.0.0",
  "scripts": {
    "postinstall": "frontend-dependencies"
  },
  "devDependencies": {
    ...
    "babel-plugin-namespace-amd-define": "^1.4.2",
    "frontend-dependencies": "^1.0.0",
    ...
  },
  "dependencies": {
    "bootstrap-select": "^1.12.4",
    "bootstrap-validator": "^0.11.9",
    "enquire.js": "^2.1.6"
  },
  "frontendDependencies": {
    "target": "src/js/plugins",
    "packages": {
      "enquire.js": {
        "src": "dist/enquire.min.js"
      },
      "bootstrap-select": {
        "src": "{dist/js/bootstrap-select.min.js,dist/js/bootstrap-select.js.map}"
      },
      "bootstrap-validator": {
        "src": "dist/validator.min.js"
      }
    }
  }
}

```

After that, I run babel as gulp hook to transpile my custom JavaScript and to run [babel-plugin-namespace-amd-define](https://github.com/liferay/liferay-npm-build-tools/tree/master/packages/babel-plugin-namespace-amd-define) as suggested by @izaera .

In my **gulpfile.js**, I run it once for my JS and next on plugin sources, in order to transform every `define` in a `Liferay.Loader.define()`:

```
liferayThemeTasks.registerTasks({
  gulp: gulp,
  hookFn: function(gulp) {
    gulp.hook('before:build:base', function(done) {

      gulp.src('src/js/modules/original/*.es.js')
        .pipe(babel({
          presets: ['es2015'],
          plugins: ['transform-es2015-modules-amd','namespace-amd-define'],
          moduleIds: true,
          moduleRoot: 'my-modules'
        }))
        .pipe(gulp.dest('src/js/modules/transpiled/'));

      gulp.src('src/js/plugins/**/*.js')
        .pipe(babel({ plugins: ['namespace-amd-define'] }))
        .pipe(gulp.dest('src/js/plugins/'));

      done();
    });
  } // hookFn
});
```
In the end, I've set up a **config.js** file to set up Liferay AMD modules:
```
// MODULE_PATH is supplied adding the Provide-Capability
// property inside liferay-plugin-package.properties
__CONFIG__.paths['my-plugins'] = MODULE_PATH+'/js/plugins';
__CONFIG__.paths['my-modules'] = MODULE_PATH+'/js/modules/transpiled';

// jQuery built inside the portal exposed as an AMD module
Liferay.Loader.define('jquery', function(){
  return window.jQuery;
});

Liferay.Loader.addModule({
  name        : 'bootstrap-validator',
  dependencies: ['jquery'],
  anonymous   : true,
  path        : 'my-plugins/validator.min',
  exports     : 'jQuery.fn.validator'
});

Liferay.Loader.addModule({
  name        : 'bootstrap-select',
  dependencies: ['jquery'],
  anonymous   : true,
  path        : 'my-plugins/bootstrap-select.min'
});

Liferay.Loader.addModule({
  name        : 'enquire',
  dependencies: [],
  anonymous   : true,
  path        : 'my-plugins/enquire.min'
});
```
Portion of **src/WEB-INF/liferay-plugin-package.properties**:
```
...
Liferay-JS-Config=/js/config/config.js
Provide-Capability=osgi.webresource;osgi.webresource=my-theme
...
```

Again: probably this is not the best solution, but it works so far.
Let me know if you have any better ideas.

Thank you!

**Comment by duracell80** [comment]
I've seen this in my local environment that is patched up to DE39, but not Production or QA which is at DE28.
Just to clarify, if we're using third party JavaScript, do we need to have the checkbox ticked or un-ticked for our libraries to continue working?

**Comment by antonio-ortega** [comment]
Hi @duracell80 ,

To preserve the same behaviour you had before installing fixpack-de-[37|38|39] you need to keep checked "Expose Global" option in System Settings > Foundation > Javascript Loader.

In any case, if you are an Entreprise Customer we would recommend you to ask this kind of questions in LESA in such a way a support engineer can provide you with a complete answer (i.e. notifying when the fix is included in a fixpack).

Thanks!
