### ISSUE TITLE
Liferay npm React portlet - problem using npm libraries 

### ISSUE THREAD

**Issue by bosna387** [liferay/liferay-amd-loader#207]
Hi All,

I have a problem thats bugging my head for awhile now. I want to use React in portlets but it seems insanely hard. Without adding libraries such as react-bootstrap-table portlet loads fine.
As soon as I want to use npm libraries such as react-bootstrap-table or datatables.net (i guess libraries that use jquery) I get missing constraints problems. Browser console error is:
Missing version constraints for react-npm-portlet$events in package.json of react-npm-portlet$react-bootstrap-table@4.3.1"
    jQuery 2
        _getResolutionError
        require
And I get blank portlet. No table shown. Importing other npm libraries such as moment etc work fine. It is only these table related libraries that dont compile well.
I have tried other npm libraries but same errors. What am I doing wrong. How do I import and use npm libraries that do tables into liferay.
I am using blade sample liferay npm react (https://github.com/liferay/liferay-blade-samples/tree/7.1/gradle/apps/npm/react-npm-portlet) here is my index.es.js (i have only changed index.es.js and package.json in the sample)
import React from 'react';
import ReactDOM from 'react-dom';
import {BootstrapTable, TableHeaderColumn} from  'react-bootstrap-table';
var products = [{
    id: 1,
    name: "Product1",
    price: 120
}, {
    id: 2,
    name: "Product2",
    price: 80
}];
`export default function(elementId) {
`  ReactDOM.render(<BootstrapTable data={products} striped hover>
`  <TableHeaderColumn isKey dataField='id'>Product ID</TableHeaderColumn>
` <TableHeaderColumn dataField='name'>Product Name</TableHeaderColumn>
`  <TableHeaderColumn** dataField='price'>Product Price</TableHeaderColumn>
`</BootstrapTable>,** document.getElementById(elementId));
`}

Package.json
{
    "dependencies": {
        "react": "15.6.2",
        "react-bootstrap-table": "^4.3.1",
        "react-dom": "15.6.2"
    },
    "description": "React Portlet",
    "devDependencies": {
        "babel-cli": "^6.26.0",
        "babel-preset-env": "^1.7.0",
        "babel-preset-react": "6.24.1",
        "liferay-npm-bundler": "^2.0.0"
    },
    "main": "lib/index.es.js",
    "name": "react-npm-portlet",
    "private": true,
    "scripts": {
        "build": "babel --source-maps -d build/resources/main/META-INF/resources src/main/resources/META-INF/resources && liferay-npm-bundler"
    },
    "version": "1.0.0"
}

All i did was in the root folder npm i react-bootstrap-table to install the library. Is there additional step that I am missing?

Appreciate your help.

**Comment by izaera** [comment]
We will tackle this in the https://github.com/liferay/liferay-js-toolkit/issues/350 as it looks more like a build time problem. :-)
