### ISSUE TITLE
Be able to config the verbose level of loader

### ISSUE THREAD

**Issue by victorg1991** [liferay/liferay-amd-loader#212]
Currently, there is only an option to enable the verbose log in the loader, but it results in the browser console bloated with too much information. It would be nice to configure the log level with at least two level: the current one, and one that shows only errors

Thanks!

**Comment by victorg1991** [comment]
grasias de antebraso

**Comment by victorg1991** [comment]
@boton

**Comment by izaera** [comment]
See https://issues.liferay.com/browse/LPS-101559 too
