### ISSUE TITLE
Liferay AMD Loader doesn't support arrow function

### ISSUE THREAD

**Issue by ibhlool7** [liferay/liferay-amd-loader#213]
I tried to use the arrow function in my react application but in deployed time, I got an error with the arrow function, the arrow symbol wasn't resolved.

**Comment by yuchi** [comment]
Arrow functions are not something that must be “resolved”.

If you are targeting an environment that doesn‘t support ES2015 (called also “ES6”) features such as arrow functions, you need to _transpile_ them. Old browsers have this problem. You can use [Babel](https://babeljs.io/) for this kind of issues.

Can you paste here the error you found? Probably you are missing a build step, and ES2015 code is being minified in the Portal (which supports only ES5 code).

**Comment by ibhlool7** [comment]
I use "clean" in the Gradle module option and deploy it again and it works.
thank you @yuchi
