### ISSUE TITLE
Issue with import in v 4.1.0

### ISSUE THREAD

**Issue by ibhlool7** [liferay/liferay-amd-loader#214]
Hello
I'm using the last version of Liferay AMD loader (4.1.0) and the last version of Liferay NPM bundler (2.11.0).
You can get this error simply by following steps : 
1. create a npm-react-portlet module (I'm using Liferay plugin on Intellij Idea)
2. create a simple component as bellow in ' \META-INF\resources\lib\components 'directory:
```
import React from 'react'

class Test extends React.Component {
    render() {
        return <div><h1>Hello world</h1>
            <p>I'm here</p></div>;
    }
}
export default Test;
```
3. import this component in index.es.js
`import Test from 'components/Test'
`
4. try to deploy and use this portlet in Liferay and BOOM, you don't see anything in your portlet and when you check your browser console you can see the following error :

```
(index):2418 Error: Unsatisfied dependency: two-version$components/Test found in module two-version@1.0.0/lib/index.es
    at loader.js:577
    at Array.map (<anonymous>)
    at loader.js:562
    at Array.forEach (<anonymous>)
    at e.value (loader.js:528)
    at loader.js:344

```
I've tested it on Opera and Google Chrome .
thank you

**Comment by izaera** [comment]
If you are placing `Test` under `META-INF/lib/components`, why would `import Test from 'components/Test'` work? :thinking: 

Why are you removing `lib` from the path?

**Comment by ibhlool7** [comment]
this is my directory structure 
![rel](https://user-images.githubusercontent.com/29673016/62280474-3c6b4080-b461-11e9-92c3-112c3cbb9f88.PNG)
I've changed my component import in index.es.js as below 
`import Test from './components/Test'
`
and got the below error in my browser console  
```
(index):1163 Error: Unsatisfied dependency: ./components/Test found in module React-simple-project@1.0.0/lib/index.es
    at loader.js:577
    at Array.map (<anonymous>)
    at loader.js:562
    at Array.forEach (<anonymous>)
    at e.value (loader.js:528)
    at loader.js:344
```

**Comment by naderjafari** [comment]
Hi @izaera 
I have similar problem with version 4.0.0
is that a bug? or somethings is wrong in this way of "Import"?

**Comment by izaera** [comment]
Hi there. I need to find some time to look at this issue but we are very busy right now :-(.

However I doubt that this is a real issue with the loader or the bundler, because everybody (us included) is using relative imports begining with `./` and they work so it must either be a very specific thing, or some other piece of the build chain that is failing.

To finish with, the proper place to file these issues would be either the `Liferay plugin on Intellij Idea` bug tracker or the Liferay Portal one. This project is too low level and, as I said, there could be lots of things happening before the loader (or even the bundler) kicks in to make this fail.

**Comment by naderjafari** [comment]
Hi @izaera
I can create and share sample project to save your time.
But I think this is a bug in new version.  because this issue does not occur in 4.0.0 version that is built-in version in liferay 7.2 and 7.1 last release

**Comment by izaera** [comment]
@naderjafari OK, that would be good. If you can send a ZIP with the project I can the build in my laptop and report the results. Thx :-).
