### ISSUE TITLE
CSS importing issue

### ISSUE THREAD

**Issue by ibhlool7** [liferay/liferay-amd-loader#215]
Hello

There is a problem with importing CSS in theV4.x Liferay AMD loader!
I try to import CSS file from different directories like :
` \resources\META-INF\resources\css `
or 
`\META-INF\resources\lib\css`
but when the portlet runs I get an error message in browser console like following : 
`Error: Unsatisfied dependency: import_test$css/test.css found in module import_test@1.0.0/lib/index.es`
The structure is here :
![t](https://user-images.githubusercontent.com/29673016/62197622-6bb47b80-b395-11e9-936c-65cf060fa5a3.PNG)
test.css code is liked below :
```
.Button{
    padding: 10px 5px;
    background-color: aqua;
}
```
and in index.es.js, the test.css imported like below :
`import 'css/test.css'`

thanks

**Comment by izaera** [comment]
The loader is an AMD loader, so it only knows how to handle JS. This must be solved at the tooling level and it's being addressed in this issue -> https://github.com/liferay/liferay-js-toolkit/issues/303
