### ISSUE TITLE
Rename the project to liferay-amd-loader

### ISSUE THREAD

**Issue by ipeychev** [liferay/liferay-amd-loader#44]

**Comment by ipeychev** [comment]
Hey @jbalsas,

The project should be renamed, since the repository has been renamed too. Will do that now.

Thanks,

**Comment by jbalsas** [comment]
Hey @ipeychev, I didn't rename the project intentionally, so people still using it could still use it. 

Right now, if someone was using it, he'll never be able to automatically grab the new versions, would he? Is there a way to notify the deprecation of a module so people will at least get warnings pointing to the new name?

**Comment by ipeychev** [comment]
Yes, I added such deprecation message, so when you install it, you will see it.

**Comment by jbalsas** [comment]
Oh, really? Did I miss it in the commits or is it something you do when publishing to npm?

**Comment by yuchi** [comment]
It's something you add through npm itself.

**Comment by jbalsas** [comment]
Ok, thanks guys! :+1:
