### ISSUE TITLE
Feature request: specifing a function to transform module names, similar to map

### ISSUE THREAD

**Issue by willywongi** [liferay/liferay-amd-loader#46]
I would like to configure the loader in order to translate module names with a custom function, eg.:
```javascript
__CONFIG__.replacements = {
    "^vendor\.": function(name) {
        return name + ".min";
    }
}
```
As you can see from this example, it would be nice to have a mapping between names/regexps and functions, so that I could only translate some of the module names.

**Comment by ipeychev** [comment]
Mmm, but there is `maps` where you can specify module names mapping. Doesn't that work for you?

**Comment by willywongi** [comment]
It works indeed, but I should know beforehand all the module names, and update this list everytime I add another module. Well, I actually know all the module names, so now I do can use maps; with a function like that I would move the burden of resolving module names from the moment when I prepare the __CONFIG__ object to the moment when the loader actually load them.
I can understand if you prefer not to add complexity to this later moment: it's your call, you're the boss ;)

**Comment by ipeychev** [comment]
Yes, that is it - reading the requirement, I felt it should be doable even now. I'm OK to extend this and add more sugar methods, config, etc. it won't hurt to some degree, after that people start to get confused.
In any case I'm not going to refuse this change, just the opposite. Could you post some example code what are you doing now, maybe we can invent a better API than `__CONFIG__.replacements`?
Maybe we can even make `__CONFIG__.maps` to be either a function or an object. If function, we will pass the name of the module and expect the mapped module?

**Comment by willywongi** [comment]
The mighty YUI Loader had a [vast configuration](http://yuilibrary.com/yui/docs/yui/loader.html) (sometimes poorly documented). But it allowed to define patterns to match the module names and a `configFn` to change the module name, path and type.
I'm writing a more complete example and posting it here, so we can start working on it from there.

**Comment by willywongi** [comment]
https://gist.github.com/willywongi/ab2d3d1cac7b03f8512f

I wrote 3 suggestion for this API: this is nothing that can't be done with the current API (`__CONFIG__.maps`), but could be useful to change some module configuration at runtime.

**Comment by ipeychev** [comment]
I somehow feel confusing that there will be more than one place where module name will be mapped.
I think mapping should happen from one place - from `maps`.
What if we do it in this way:
```
__CONFIG__.maps = {
    a: 'b',
    c: 'd',
   '*': function(name) {
        if (/^acme/.test(name) && ! /\.min$/.test(name)) {
		return name + ".min";
	}
	return name;
   }
};
```

i.e. first we look for an explicitly set module mapping and if not found, we look for an asterisk which value could be a function which will do the transformation?

**Comment by willywongi** [comment]
Sure! It will do!

**Comment by ipeychev** [comment]
@jbalsas Might be this will be useful for you too.

**Comment by jbalsas** [comment]
Hey @ipeychev, yeah I was definitely considering this could be useful for us too. I'll update our loader version asap to make sure we ship with this feature :)

**Comment by ipeychev** [comment]
:+1:
