### ISSUE TITLE
Promise polyfill does not work in IE11

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-amd-loader#55]
The polyfilled version `loader.js` is not auto-polyfilling `Promise`, so it doesn't work in IE.

**Comment by ipeychev** [comment]
Hey Chema,

This version indeed does not auto-polifying `window.Promise`. Here the developer was supposed to call explicitly `window.ES6Promise.polyfill()` and then it would create an `window.Promise` polyfill. Definitely far away from the expected behavior.

Thanks,

**Comment by ipeychev** [comment]
Okay, [here](https://github.com/liferay/liferay-amd-loader/releases/tag/v1.4.3) it is the new version (1.4.3).
I changed only one thing - to retrieve the non-minified version of ES6 Promise instead the minified one. In any case we create both minified and non-minified versions of the Loader, so it is better to not use minified versions of third party libraries - you never know what is inside and how do they minified it.

Thanks,
