### ISSUE TITLE
Problem mixing required modules and pre-loaded modules

### ISSUE THREAD

**Issue by willywongi** [liferay/liferay-amd-loader#58]
I was hoping to be able to pre-load modules adding a static script tag in my HTML. 
```html
<html>
<head>
<script src="path/to/loader/and/config"></script>
<script src="http://mycomboserver.com?module1.min.js&module2.js"></script>
<script>
require(['module1', 'module2', 'module3'], function(m1, m2, m3) {
// ...
});
```
This is incredibly useful for developing and debugging files before adding them to the combo-loader. As a partial workaround I added a _requested_ parameter resolves:
```js
define('module1', [], function() {
// implementation
}, {requested: true})
```
This is OK while developing, but I was looking for a more clean solution; other than that, I'm working with a quirky, huge, 3rd party library and I need to preload some files that I cannot tamper with.
```js
define('module2', [], function() {
// this file I cannot touch.
});
```
Any help would be much appreciated.

**Comment by ipeychev** [comment]
Hello,

This would work if these modules were ES2015 and they were registered in the config file, but it seems this is not the case.
From what I see, these are general AMD modules and you don't know anything about them - if they export something, or not, don't you?
I think one option could be to run the config generator and process these modules in order to register them in the config file. Then, requesting them via URL should be fine.

Does that make sense?

Thanks,

**Comment by willywongi** [comment]
Ciao! I realized that my example was definitely not clear about my issue; second try!
I'm working with this library (KendoUI) that I can, for the most part, load using your loader and the same combo loader of the good ol' YUI days. I build a config file parsing all the files (both KendoUI files and my custom files) for module names and requirements. All these files are hosted in the same path in my combo-server.
Sometimes though I would like to static load (ie.: manually add a script tag to my page) one or more of those modules: this would help me in two cases.
1. I want to override one of my modules to use a different version; the file would be hosted somewhere else (ie. on my own dev server, not on a combo-loader)
2. Some of the KendoUI modules are not behaving: they `define` a number of modules in the same file and some of these require those just defined modules:
```js
define('util/stuff', [], fn);
define('util/otherstuff', [], fn);
// ...
define('grid', ['util/stuff', 'util/otherstuff'], fn);
```
So when I `require(['grid'])` the loader tries to load inexistent files (`util/stuff.js&util/otherstuff.js`), causing the required module not to load.

I managed to resolve (1) adding `{requested: true}` at the end of the definition, but I can't resolve (2): I would happily avoid manually splitting KendoUI files to obtain the "one file - one module" configuration.
If any defined module (loaded statically or dinamically) would register itself, I could resolve both problems.

Thank you for your help!

**Comment by ipeychev** [comment]
Hello,

Okay, so you are parsing and generating a config file from all the modules, that is good. If the modules are described in the configuration and they are not anonymous ones (as in your case), they should be properly loaded, despite they are in same file. And I think even if you load them via static file, and request them later they should be loaded properly (and I think we have tests for that).

So, could you provide an example somehow (CodePen or here as an zipped file)? This will help us to reproduce the issue and fix it.

Thanks,

**Comment by willywongi** [comment]
I found other oddities in the KendoUI files (duplicate module declaration scattered through a lot of files), so for now I give up on problem 2.
But I built an example of what I was saying: even if I provide in the page the definition of a module, when I require it, the loaders fetch it again. Please notice that this happens only when `combine` is true.
In the [attached zip file](https://github.com/liferay/liferay-amd-loader/files/219210/liferay-amd-loader-issue-58.zip) you'll find:
- a simple python webserver with combo loading;
- the loader from last commit (7f0225610099a1e34510d986811200140303f783)
- index.html, module1.js and module2.js

Start the server (`python dummy-server.py 12345`) and visit `localhost:12345`. In `index.html` the two modules are configured, then `module2` is included. Then, both are require

d, but, despite having already defined `module2`, both are fetched through a combined request.

> 15:15:00.826 DEFINE module2 Array [  ] loader-pure-debug.js:884:9
> 15:15:00.835 No listeners for event: moduleRegister loader-pure-debug.js:96:13
> 15:15:00.841 REQUIRE CALLED loader-pure-debug.js:967:9
> 15:15:00.842 REQUIRE called with Array [ "module1", "module2" ] loader-pure-debug.js:999:9
> 15:15:00.842 REQUIRE modules mapped to Array [ "module1", "module2" ] loader-pure-debug.js:1006:9
> 15:15:00.844 REQUIRE dependencies resolved to Array [ "module1", "module2" ] loader-pure-debug.js:1014:17
> 15:15:00.846 SCRIPTS Array [ Object ] loader-pure-debug.js:1300:17
> 15:15:00.964 DEFINE module1 Array [  ] loader-pure-debug.js:884:9
> 15:15:00.965 No listeners for event: moduleRegister loader-pure-debug.js:96:13
> 15:15:00.966 DEFINE module2 Array [  ] loader-pure-debug.js:884:9
> 15:15:00.966 No listeners for event: moduleRegister loader-pure-debug.js:96:13
> 15:15:00.967 No listeners for event: scriptLoaded loader-pure-debug.js:96:13
> 15:15:01.070 [willywongi] module1 loaded module1.js&module2.js:3:2
> 15:15:01.071 [willywongi] module2 loaded module1.js&module2.js:12:2
> 15:15:01.071 REQUIRE promise success loader-pure-debug.js:1040:13
> 15:15:01.071 done! localhost:12345:25:4

**Comment by ipeychev** [comment]
Awesome, will take a look now

**Comment by ipeychev** [comment]
Okay, it is clear now.
First of all, that is not related to the `combine` flag - in both cases the loader requests `module2`.
The problem is that when module is being loaded explicitly (via `script` element), we don't set the flag that it was requested. That is correct, but because this flag is missing, when module is required, it is being retrieved despite it has implementation. In this case, it shouldn't be requested.
I will fix this and release a new version.

Great bug report btw, maybe the best one I've ever seen in my career.

Thanks,

**Comment by willywongi** [comment]
I was ashamed for the opening of the issue, it was really unclear and inaccurate, so I put myself into making it crystal clear. 

> Great bug report btw, maybe the best one I've ever seen in my career.

I'm blushing...

**Comment by ipeychev** [comment]
Fixed and [released](https://github.com/liferay/liferay-amd-loader/releases/tag/v1.4.4) v1.4.4
