### ISSUE TITLE
add support for loading anonymous module definitions

### ISSUE THREAD

**Issue by bkardell** [liferay/liferay-amd-loader#60]
Being able to load existing anonymous module definitions that are not liferay hosted would seem to be a critical feature of an AMD loader, but this is currently unsupported, therefore artificially adding a limitation preventing the use of a vast ecosystem of modules without significant changes to modules and hosting.  Since liferay is providing an AMD loader and two AMD loaders can't co-exist (really shouldn't co-exist because they are intended to be compatible), it would seem that having a fully capable AMD loader would be much more advantageous than not.  For many clients (mine included) this is kind of critical in creating a path for moving complex existing content to liferay.

**Comment by ipeychev** [comment]
On Apr 21, 2016 17:06, "Brian Kardell" <notifications@github.com> wrote:
>
> Being able to load existing anonymous module definitions that are not
liferay hosted would seem to be a critical feature of an AMD loader, but
this is currently unsupported, therefore artificially adding a limitation
preventing the use of a vast ecosystem of modules without significant
changes to modules and hosting. Since liferay is providing an AMD loader
and two AMD loaders can't co-exist (really shouldn't co-exist because they
are intended to be compatible), it would seem that having a fully capable
AMD loader would be much more advantageous than not. For many clients (mine
included) this is kind of critical in creating a path for moving complex
existing content to liferay.

Alright, we will figure this out. I saw you contacted the support, they
will get more information about your environment and we will move forward
accordingly.

Thanks,
Iliyan

**Comment by ipeychev** [comment]
We will take a look.
Last time I read the [specification](https://github.com/amdjs/amdjs-api/blob/a731da21e218b44d16182683a829b376f336ffbd/AMD.md) (if that can be called a specification at all) I got confused by two things, both of them related to the anonymous modules:
1. What should happen if there are multiple anonymous modules in a file, which one wins?
2. What should happen if there is anonymous module in a file, but the user explicitly adds this file via `script` element?

**Comment by bkardell** [comment]
cc @jrburke to keep me honest/make sure I'm not misrepresenting something

> 1. What should happen if there are multiple anonymous modules in a file, which one wins?
This isn't done/possible - seems nonsensical, I would expect it to throw.  Believe require throws  MismatchedAnonymousDefine.  If you want to put multiple modules in a bundler, the bundler names them.  r.js and many others do this.  

> 2. What should happen if there is anonymous module in a file, but the user explicitly adds this file via script element?
Because of how the loader keeps track of and defines anonymous modules (they are queued and realized only after their deps are loaded iirc, define is a two-step) I do not believe this is possible in any AMD system. I do seem to recall a discussion from a few years back where someone was suggesting normalizing advice on that for all of the loaders and IIRC there was agreement that this just wasn't going to work as there is really no way to pair the module back?  In any case, I've never seen that done with any system, I'm not sure anyone would have existing experience telling them that should work?

Realistically, I think that that last sentence is the key here - what are the de facto expectations.  No need to surpass those, but meeting/matching them would be ideal.

**Comment by jrburke** [comment]
@bkardell has represented correctly.

**Comment by ipeychev** [comment]
>  > ipeychev: What should happen if there are multiple anonymous modules in a file, which one wins?

> bkardell: This isn't done/possible - seems nonsensical, I would expect it to throw. Believe require throws MismatchedAnonymousDefine. If you want to put multiple modules in a bundler, the bundler names them. r.js and many others do this.

For the record, this is incorrect. Please unzip the attached file and check what index.js prints inside the console.
[requirejs-test.zip](https://github.com/liferay/liferay-amd-loader/files/233005/requirejs-test.zip)

**Comment by jrburke** [comment]
It is true that example does not throw mismatched define, that will occur if a separate script tag is attached outside the loader, and then the loader tries to load modules and finds that anonymous define in the queue.

The part where I said @bkardell represented correctly was the "seems nonsensical" part. There is no way for the loader to assign correct names to all those modules. It would be like if someone just concatenated a bunch of CommonJS or ES2015 modules together without giving them names and boundaries. However each one of those module formats supports an anonymous form for single module loads.

It might be helpful for requirejs to throw in this case, and I think it is fine if an AMD loader wanted to do so in this case.

**Comment by ipeychev** [comment]
@bkardell @jbalsas 
I think this should do it, could you please take a look?
Please keep in mind that anonymous modules cannot be loaded from a combo URL and in this case, even if `combine` is set to `true` every anonymous module will be excluded from the combo URL and a separate `script` element will be created for it.

Thanks,

**Comment by jbalsas** [comment]
Hey @ipeychev , thanks so much for all the work!! I'll take a closer look in the following days to make sure I understand the new feature.

We have a meeting on Wednesday, so I think we can evaluate the situation and make the necessary adjustments or just release this version if that's enough.

Thanks again!

**Comment by bkardell** [comment]
I think I am doing this right, spoke to Chema at Liferay, sounds like he does too.

I made this trivial little pen to demonstrate... http://codepen.io/bkardell/pen/LNgEyJ

To summarize:  
* Page defines a map fn with * - it uses this to map a name to a url
* Page requires module 'b' to a url
* 'b' is an anon define which requires 'a'
* requests are made for b, then a, but never resolved.

It looks to be like what is happening is that it is attempting to map back to the URL, treating that as the module name based on the scriptLoaded and you wind up trying to map A twice and the real 'a' is never properly completed.

Assuming this is correct, I'd like to re-open this issue.  IIRC, requirejs uses a data attribute when creating the script to include the module name so that it can be tracked back properly.  In your case, I'm not actually sure that's necessary as you can maybe close over it in the event (I haven't looked closely at your event thing tho to see how much impact that would have).

**Comment by ipeychev** [comment]
It works, your configuration is wrong, please check the attached file.
[index.html.zip](https://github.com/liferay/liferay-amd-loader/files/239318/index.html.zip)

**Comment by bkardell** [comment]
Excellent to hear.  Because we don't want you to have to know an entire set of dependency tree mappings before using, I'm planning on using map ['*'] to set it - it will regexp check to see if it looks like 'our' modules which all follow a fairly unique convention as per http://codepen.io/bkardell/pen/LNgEyJ --- see any issue with that?

**Comment by ipeychev** [comment]
You have to use `paths`, not `maps`, because what you want is to explicitly tell the loader where to load the files. There are __three__ ways to achieve what you want:
1. You specify in the config the path to the modules explicitly:
```javascript
__CONFIG__ = {
    paths: {
        a: 'https://rawgit.com/bkardell/gaps/master/a.js',
        b: 'https://rawgit.com/bkardell/gaps/master/b.js'
    }
};
```
2. You specify a common URL for your modules via the `url` property:
```javascript
__CONFIG__ = {
    url: 'https://rawgit.com/bkardell/gaps/master/'
};
```
3. You use a function in order to specify whatever path you want to the modules:
```javascript
__CONFIG__ = {
    paths: {
        '*': function(module) {
            return 'https://rawgit.com/bkardell/gaps/master/' + module + '.js';
        }
    }
};
```

Hope that helps.

Thanks,

**Comment by bkardell** [comment]
@ipeychev did you look at the codepen? there, I am using maps simply to get the '*' fn feature - but it is manipulating paths, not maps.  I didn't see the * fn feature documented anywhere, I found it in the code.  Looking now even I am not seeing a similar * fn handling for paths.  Does that exist?  Am I missing it?  Is there an issue abusing maps * like I am for that purpose?  The pen works as is, doesn't work trying to use * on paths that way....  Note I am also getting the thing through the accessor because I appeared to be experiencing some raciness with __CONFIG__ but that could be a red herring with all the other issues.... If I should be doing it as above and that works I'm happy to change - using an updated build of liferay and the above approach (capturing with maps * and modifying paths) is successfully initiating requests for a bunch of stuff, but I'm still hitting a failure before the outermost module is completed - could be me, I'll let you know if it isn't.

**Comment by ipeychev** [comment]
The `*` in both `maps` and `paths` exists. In `maps` it wasn't documented (not intentionally, please feel free to contribute), and I just added the `*` support in paths in [this](https://github.com/liferay/liferay-amd-loader/commit/6ea2ffd33e437170a328535ebe4340fd298ac48c) commit. If you use the master version of loader, you will be able to do it with any of the three ways, described above. We will release ver. 1.5.0 soon with anonymous module support and Liferay will be updated too.

__CONFIG__ should be specified before Loader's script file. Get the `index.html` which I uploaded recently, use some of the methods above and have fun.

Thanks,

**Comment by jbalsas** [comment]
Thanks a lot for the help @ipeychev!!

@bkardell, I'll generate a new module with the updated `*` support in paths for you to try that avenue as well.
