### ISSUE TITLE
Requiring a module second time together with another one fails

### ISSUE THREAD

**Issue by ipeychev** [liferay/liferay-amd-loader#61]
This scenario fails:
```javascript
Loader.require(['module3'], success, failure);
Loader.require(['module3', 'module7'], success, failure);
```

It fails because the second module is marked improperly as already requested

**Comment by willywongi** [comment]
I spent the last few days looking into the same issue, I just came here to open it and found it already resolved. Wow, I sense the planets aligning. :+1:

**Comment by ipeychev** [comment]
Great!
