### ISSUE TITLE
Add option to pass parameters in the request url

### ISSUE THREAD

**Issue by brunobasto** [liferay/liferay-amd-loader#72]
Hey @ipeychev,

How is it going?

I wanted to know if it's possible to pass in parameters to the scripts' url. I want every request to have a parameter, so, in the config I would do something like:

`window.__CONFIG__ = {
	basePath: '',
	combine: false,
        params: {
            languageId: 'en_US'
        },
	reportMismatchedAnonymousModules: 'warn',
	url: baseURL
};`

and when I do:

`require('myapp/main, function() {})`

the loader would request:

http://localhost:8080/myapp/main.js?languageId=en_US

**Comment by ipeychev** [comment]
Hey Bruno,

Everything is fine, thanks! I hope everything is OK with you too.

Currently we can't do it, but it would be trivial to achieve it - we have to modify [this](https://github.com/liferay/liferay-amd-loader/blob/master/src/js/url-builder.js) class.

**Comment by brunobasto** [comment]
I would love to become a contributor :)

I'll send you a PR soon. Thank you!

**Comment by ipeychev** [comment]
Great! You may also rename this `params` which is too common to something like `defaultURLParams`.
