### ISSUE TITLE
NPM and Bower Modules

### ISSUE THREAD

**Issue by TBurk83** [liferay/liferay-amd-loader#79]
Can this load modules installed via NPM or Bower? If so, it would be helpful to have instructions for this in the docs. Most developers are not going to use only Alloy UI.

If not, is there a way to disable this module loader in Liferay? It interferes with AMD-aware scripts referenced in Liferay themes.

**Comment by jbalsas** [comment]
Hey @TBurk83, please, see https://github.com/liferay/liferay-amd-loader/issues/78 and https://web.liferay.com/es/community/forums/-/message_boards/view_message/78023198#_19_message_79831511

**Comment by TBurk83** [comment]
Thanks @jbalsas! Glad you guys are aware of the issue.

Is there any good documentation regarding using this module loader with a Liferay portlet or theme? Most of the documentation here seems geared toward users just pulling from this repo and using the loader standalone, rather than working with what's running OOB with Liferay.

**Comment by jbalsas** [comment]
Hey @TBurk83, this project aims to be exactly that, a **standard, amd-compliant, standalone loader**. You can use it in your projects (as others are doing) if you wish.

For Liferay Portal specifics, you can read our [existing documentation](https://dev.liferay.com/develop/tutorials/-/knowledge_base/7-0/javascript) or navigate the [official forums](https://web.liferay.com/es/community/forums) where I'd be happy to answer any question you have as well! 😉

**Comment by TBurk83** [comment]
@jbalsas 

So there won't be any documentation forthcoming that explains the best practices for using this module loader, with Liferay themes and portlets, with popular frameworks like React, Angular 2, etc. ?

**Comment by jbalsas** [comment]
Of course it will, just not on this repo.

The [existing tutorials in the Developer Network](https://dev.liferay.com/develop/tutorials/-/knowledge_base/7-0/javascript) already show how you can write modules in Liferay using ES2015 and how you can require them using the loader and other infrastructure. Is there something in there you feel missing?

We're exploring what it takes to integrate with the frameworks you mention, and we'll make sure to publish the documentation in the [Liferay Developer Network](https://dev.liferay.com/develop/tutorials) as well.

**Comment by TBurk83** [comment]
@jbalsas 

See my updated previous comment for clarification.

**Comment by yuchi** [comment]
Hi @TBurk83, I you are actually able to use React on a bundle or theme with Liferay AMD Loader right now, on the last GA of DXP and Portal.

To do that you just need to manually define your modules in the bundle (it works for themes to) by creating a configuration file that will be loaded on _every page requests_, usually called _config.js_.
In your _bnd.bnd_ file add this lines:

```ini
# This points to the configuration file
Liferay-JS-Config: /META-INF/resources/config.js
# With this your bundle owns a web context to serve resources from
Web-ContextPath: /my-bundle-name
```

Then in your _src/main/resources/META-INF/resources/config.js_ file you can add your _modules definition_ (I’m gonna show an example for React):

```js
Loader.addModule(
  {
    dependencies: [],
    name: 'react',
    anonymous: true,
    // Either this:
    path: MODULE_PATH + 'path/to/something.js'
    // or
    path: 'https://unpkg.com/react@15.3.2/dist/react.js'
  }
);
```

With the code above in every page you need React you can do the following:

```jsp
<aui:script require="react">
  // variable `react` is available here (lower case "R")
</aui:script>
```

or

```html
<script>
require('react', function (React) {
  // variable `React` is available here (upper case "R")
});
</script>
```

or (through babel compilation, which is configured by default with the typical Gradle tasks)

```js
import React from 'react';
```

- - -

That said you need to know some caveats about the current solution.

First of all you would probably define a module as `react`, and that goes in a global registry managed by the Loader. If someone else does that to the behaviour is undefined, because you don’t know which one arrives first. If both define the same version everything should work.

These kind of problems come from the fact the the Loader has no knowledge of packages. It works only with the concept of modules. That means that everything will work perfectly for you if:

1. you work with dependency-free dependencies (your dependencies don’t have dependencies themselves);
2. you only have bundles installed on you portal that either use your defined dependencies or simply define the same version again;

And lastly, be aware that anonymous modules cannot be combined through Combo Loading, and cannot be requested in batch. If you did so you would not know which one is which.

**Comment by TBurk83** [comment]
Thanks @yuchi! Exactly what I was looking for. I'll try this out.

**Comment by yuchi** [comment]
The CDN one might not work, I’m testing why.

**Comment by yuchi** [comment]
Silly me. With modules served from paths different from the base one (the Portal’s) you need to specify the `fullPath`. I fixed the example up there.

**Comment by mfreeman-xtivia** [comment]
Are the various custom bnd directives (e.g., "Liferay-JS-Config" ) related to ES6 and AMD loading documented anywhere?

**Comment by ipeychev** [comment]
I don't know what do you mean, which probably means that this question is not for here, but for Liferay's forums.

**Comment by TBurk83** [comment]
@ipeychev - That would be true if any kind of response, from someone at Liferay, was guaranteed. However, I've posted questions there regarding this module loader before and received no reply. 

This is Liferay's GitHub repo and you folks, I would think, work for Liferay or with folks at Liferay, so asking questions regarding this module loader and how it interacts with Liferay 7, of which it is a critical component, is appropriate.

**Comment by mfreeman-xtivia** [comment]
@ipeychev I am referring to the answer/recommended solution above by @yuchi. He says "To do that you just need to...etc etc" and then his example describes adding *Liferay-JS-Config* to the bnd.bnd file. I just wanted to know where all of those "magic options" for use in the bnd.bnd file are documented.

**Comment by jbalsas** [comment]
Hey @mfreeman-xtivia, we're working on documenting all those options right now. We currently cover the basic setup in the [JavaScript Tutorials](https://dev.liferay.com/develop/tutorials/-/knowledge_base/7-0/javascript). More advanced topics are still being drafted and will be published as soon as possible.

In the meantime, I've answer several questions regarding these topics in the forums where you might find some bits of info before we compile the final documentation:
- [LR7 CE GA2: import JavaScript third party lib](https://web.liferay.com/es/community/forums/-/message_boards/message/76720204)
- [DXP: Hook js file from any web module](https://web.liferay.com/es/community/forums/-/message_boards/message/80522533)
- [fragment for javascript files](https://web.liferay.com/es/community/forums/-/message_boards/message/77090513)
- [How to use Dojo with Liferay 7](https://web.liferay.com/es/community/forums/-/message_boards/message/78023198)

@TBurk83, if there is any message where I might have failed to provide a satisfactory answer (or an answer at all), please let me know and I'll try to get to it as soon as possible.

**Comment by ipeychev** [comment]
Guys, I understand your pain, but please understand mine too. This repository maintains the Liferay AMD Loader. It loads AMD modules. It doesn't know anything about any BND and it will never know.
it is not a good approach to try to solve the problem with lack of answering in Liferay Forums by asking Liferay Portal specific questions in this repository.

Thanks,

**Comment by mfreeman-xtivia** [comment]
Any ideas when this updated loader will actually make it into the Liferay 7/DXP baseline? The fact that this repo has the modification is cool, but doesn't really help me much anyway until it gets into a release of Liferay? or is that a question i should ask on the forums as well?

**Comment by jbalsas** [comment]
Hey @mfreeman-xtivia, as you fairly guessed, those questions are related to the Liferay release and support cycle, so I'd say yes, they are better suited for the forums.

Version `1.5.5` of the loader is already integrated in upstream https://github.com/liferay/liferay-portal/blob/master/modules/apps/foundation/frontend-js/frontend-js-web/package.json#L12. It has already been backported to the support branches, so it will be made available in the next fix pack if you're a customer or in the next release of the GA version.

 In addition to that, as soon as we merge https://github.com/liferay/liferay-amd-loader/issues/83 we'll proceed to release `1.5.6` and integrate it in the system with a setting that would make it possible to hide it on demand. This will follow the same release process, so you should expect it in the next fix pack after we release the version or the next GA.

Hope that helps!

**Comment by TBurk83** [comment]
@ipeychev - The fact that we're asking these questions here should tell you something about our level of confidence in getting our questions answered on the Liferay forums. Also, this, and other parts of Liferay 7/DXP, are, obviously, very new, and the only people with satisfactory answers to our questions are probably the people who built it.

I understand that you'd prefer us to not ask our questions here; we'd prefer to not have to ask these questions.

**Comment by jbalsas** [comment]
Hey @TBurk83, I understand your frustration, I really do, and I humbly apologize for my part in it 😢. I'm doing my best to monitor both our projects and the Liferay Forums, but sometimes things slip by or I just lose track of them. Again, I honestly apologize for this and would ask you to bring any outstanding issues to my attention if I've failed to answer them in a reasonable amount of time.  

We're working on both, improving the documentation in LDN as well as create an independent site for this project. We are aware of how these issues impact your day to day work and are working hard to solve it, so please, bear with us a little longer.

Also, please keep in mind that @ipeychev is not a Liferay employee, but still he's kindly contributing and maintaining this as an open source project he's very passionate about.

**Comment by yuchi** [comment]
May I suggest @ipeychev to simply assign Liferay related issues to @jbalsas?

You can cc me to, as I'd like to help in this transition moment.

**Comment by TBurk83** [comment]
@jbalsas - I apologize if I'm being overly caustic. I appreciate the responses here, even if this isn't the correct place in which to ask questions.

**Comment by jbalsas** [comment]
That's okay, @TBurk83, I understand how frustrating this can be. We'll try to answer with actions and better documentation as soon as possible.

**Comment by jbalsas** [comment]
Hey @TBurk83, @mfreeman-xtivia, just making sure we follow up, we already published a Tutorial in LDN about [Configuring Modules for Liferay Portal's Loaders](https://dev.liferay.com/develop/tutorials/-/knowledge_base/7-0/configuring-modules-for-liferay-portals-loaders). 

More documentation's coming, but I hope this helps ease the pain. 

Please let us know if you're missing something so we can work on that.

Thanks!

**Comment by mfreeman-xtivia** [comment]
I think we are still talking past one another. 

I understand and have read the doco on the modules to which you refer, but in this case I am not interested in using that. In this case lets say i want to just build a portlet that uses browserify-ed JS and no Liferay JS modules but I need to boot the Liferay AMD loader out of the global namespace so that it doesn't confuse browserify or anything else like that, which reacts poorly when someone else has latched onto require/define in the global.

Is it possible to do this somehow?

**Comment by jbalsas** [comment]
Hey @mfreeman-xtivia, I was referring to this [specific comment](https://github.com/liferay/liferay-amd-loader/issues/79#issuecomment-254630313) you made. 

I wasn't aware you had ask about the loader's visibility as well. About that, code for [LPS-68298](https://issues.liferay.com/browse/LPS-68298) is already in the master and the 7.x branch, so it should make it into the next released fix-pack for DXP as well as for the next GA. This adds a `System Setting` called `Expose Global` under the `JavaScript Loader` section that you can turn off to remove it from the global namespace.

**Comment by mfreeman-xtivia** [comment]
Perfect--thank you! that's exactly what I was searching for 👍
