### ISSUE TITLE
Load a jQuery plugin which is not an AMD module

### ISSUE THREAD

**Issue by caneta** [liferay/liferay-amd-loader#80]
Hi. I would like to load [this jQuery plugin](https://github.com/fntneves/jquery-labelauty) which is not an AMD module at all, but simply needs to be loaded after jQuery.
I found [this solution](https://github.com/requirejs/example-jquery-shim) for require.js, but I cannot make it work on a Liferay 7 GA3 environment.
Is there a way to do that?
Thank you.

**Comment by yuchi** [comment]
I believe you can do it by using the `exposes` option while defining your module with `Loader.addModule`.

**Comment by caneta** [comment]
Sorry but I cannot find the `exposes` option from the api docs [here](https://github.com/liferay/liferay-amd-loader/blob/master/api/ConfigParser.html) and [here](https://github.com/liferay/liferay-amd-loader/blob/master/api/Loader.html).
Available options seems to be only the following:
- `name` (mandatory)
- `dependencies` (mandatory)
- `path` (optional)
- `condition` (optional)
- `exports` (optional)

Could you give a minimal example, please?

**Comment by ipeychev** [comment]
The property name is `exports`.

An example for underscore could be:
```javascript
Loader.addModule({
    dependencies: [],
    exports: '_',
    name: 'underscore',
    path: https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore.js'
});
```

Looking at the code of this plugin, it seems it adds `labelauty` to jquery, doesn't it? If so, the `exports` should be 'jquery.labelauty', but I don't think the loader supports this right now. However, it shouldn't be hard to add it. Will do this now.

Thanks,

**Comment by caneta** [comment]
Ok, thanks.
How to integrate this update in a Liferay 7 GA3?

**Comment by ipeychev** [comment]
@jbalsas should know better what are the current procedures. I'm no more working for Liferay. I'm only supporting and maintaining the projects I started for free, because I have a good heart.
I will release a new version on NPM as soon as we resolve https://github.com/liferay/liferay-amd-loader/issues/78 and it will be ready for integration.

If I were you, for now I would get the dist file from [here](https://github.com/liferay/liferay-amd-loader/tree/master/dist) and directly replace the existing file, just to see if it will resolve the issue. Once Liferay is ready with the patch, I would follow their procedures for updating.

Thanks,

**Comment by caneta** [comment]
Ok, thank you @ipeychev.

**Comment by jbalsas** [comment]
Hey @caneta,

As @ipeychev said, as soon as we resolve #78 we'll release a new version of the loader. Then, we'll proceed to bring it into master using [LPS-68298](https://issues.liferay.com/browse/LPS-68298) and backport it to the next scheduled fix-pack in [BPR-7017](https://issues.liferay.com/browse/BPR-7017).

This should also be released in the next community versions as well, but I don't really have a timeline for that.

If you actually need to use it in GA3, you may be able to build the module from sources and use the [override mechanism](https://github.com/liferay/liferay-portal/blob/master/tools/osgi-marketplace-override-README.markdown)

**Comment by caneta** [comment]
I cannot access to BPR-7017, but I got it.
I think I'll go with the override mechanism.
Thank you @jbalsas!

**Comment by caneta** [comment]
@ipeychev, @jbalsas: unfortunately I cannot reproduce the labelauty example in the demo, inside the Liferay 7 GA3 environment.
Inside my theme, I've got the following `main.js`:
```
AUI().ready(
  function() {
    'use strict';
    __CONFIG__.paths['jquery-labelauty']   = '/o/ga3-theme/components/jquery-labelauty/source/jquery-labelauty';
    __CONFIG__.modules['jquery-labelauty'] = { 'dependencies': [] };

    Loader.addModule({
      name        : 'jquery-labelauty',
      dependencies: [],
      exports     : 'jQuery.fn.labelauty',
      path        : '/o/ga3-theme/components/jquery-labelauty/source/jquery-labelauty'
    });

    // Require a jQuery plugin which is not an AMD module
    require(['jquery-labelauty'], function(labelauty) {
      console.log(labelauty);
    }, function(error) {
        console.error(error);
    });
  }
);

```
In the web browser console I get the following error:
```
Error: Load timeout for modules: jquery-labelauty at
http://localhost:8080/o/frontend-js-web/everything.jsp?browserId=other&them…vascript.everything.files&languageId=en_US&b=7002&t=1474546307137:13642:37
(anonymous function) @ main.js?browserId=other&minifierType=js&languageId=en_US&b=7002&t=303:58 
```
But if I try to get `jQuery.fn.labelauty` the function is present!
```
jQuery.fn.labelauty
( options )
	{
		/*
		 * Our default settings
		 * Hope you don't need to change anything, with these settings
		 */
		var settings = $.extend(
		{
                 // ...etc...
```
What is wrong with my configuration?

**Comment by jbalsas** [comment]
Hey @caneta, we haven't released the updated loader nor integrated it, so if you're testing on a bundled GA3 you'll be missing @ipeychev's [fix](https://github.com/liferay/liferay-amd-loader/commit/8330b1fe5a66427045ab1761df2ab51af4853a59) for chained exports.

**Comment by caneta** [comment]
No, I've updated the package manually as @ipeychev suggested above!

**Comment by jbalsas** [comment]
But have you updated the loader and built a new module of `frontend-js-web` from sources?

**Comment by caneta** [comment]
No, I'm working inside a liferay-theme, so the files I've changed are the ones inside
```
liferayWorkspace/themes/ga3-theme/node_modules/liferay-amd-loader/dist/
```
But if I understand you're telling me that this is not enough and I need to use the override mechanism to substitute the loader inside the portal, isn't it?
