### ISSUE TITLE
Sourcemap missing for es6-promise.map

### ISSUE THREAD

**Issue by julien** [liferay/liferay-amd-loader#88]
Hi,

When navigating through Liferay portal with the Chrome Dev Tools open, an error is printed in the portal's console concerning `es6-promise.map`

The error looks like the following (the leading timestamp has been removed)
```
WARN  [http-nio-8080-exec-6][code_jsp:181] {code="404", msg="ProxyServlet: /o/frontend-js-web/loader/es6-promise.map", uri=/o/frontend-js-web/loader/es6-promise.map}
```

Thanks

**Comment by jbalsas** [comment]
Just to clarify, this would happen to anyone using our distributed versions [loader.js](https://github.com/liferay/liferay-amd-loader/blob/master/dist/loader.js) and [loader-debug.js](https://github.com/liferay/liferay-amd-loader/blob/master/dist/loader-debug.js) in a non-minified form.
