### ISSUE TITLE
Creating a Shim for a jQuery plugin

### ISSUE THREAD

**Issue by mfreeman-xtivia** [liferay/liferay-amd-loader#89]
What is the correct style for creating a shim for a jQuery plugin that is not naturally AMD-ified? In particular I am struggling with what to set the value of 'exports' to? so I created something like this in my config.js...

Loader.addModule({
    dependencies: [],
    name: 'jquery',
    path: MODULE_PATH + '/js/jquery-2.2.3.js'
});

Loader.addModule({
    dependencies: ['jquery'],
    name: 'modal-bs',
    exports: 'jQuery.fn.modal',
    path: MODULE_PATH + '/js/modal.js'
});

...and I can see that the code in modal.js is triggered by putting breakpoints in it---but any code that has 'required' a dependency on module 'modal-bs' never fires---indicating to me that the module loader must never think that the module loading is complete...?

Everybody in the world's examples for shimming use require-js config formats as examples which doesn't really help me here...

thanks

**Comment by ipeychev** [comment]
Hello,

If the loader doesn't throw an error like `Error: Load timeout for modules: modal-bs` then the module should be loaded successfully.
You may subscribe to the failure callback of the require function to see if there is an error. Also check if the browser is able to retrieve all the files.

If this doesn't help - please add reproducible code.

Thanks,

**Comment by mfreeman-xtivia** [comment]
@ipeychev  I guess my question was more geared toward trying to understand how the loader uses the 'exports' field in the case of non-AMD modules. 

I presume from what I've read that somehow the loader checks the global after parsing the js file and if my exports was set to 'foo' it is going to look for the presence of 'foo' as a variable on the global to know if it succeeded? finished?

And does that work for dotted notation? in the case of a jquery plug that only sets $.fn.foo can I specify 'jQuery.fn.foo' in that exports field and have it work as well?

**Comment by julien** [comment]
Hi @mfreeman-xtivia ,

Since these modules are anonymous, maybe you could try the following:

```javascript
Loader.addModule({
    dependencies: [],
    name: 'jquery',
    path: MODULE_PATH + '/js/jquery-2.2.3.js'
});

Loader.addModule({
    dependencies: ['jquery'],
    anonymous: true,
    name: 'modal-bs',
    path: MODULE_PATH + '/js/modal.js'
});
```

It's also important to keep in mind, that loading anonymous modules via combo URL is not possible.

I also thought that this [stackoverflow post](http://stackoverflow.com/questions/39490126/jquery-plugin-in-a-liferay-7-theme/39515106#39515106) might be useful.

If you load your jQuery plugin as a global, you'll probably be able to access it via `$.fn.foo` or `jQuery.fn.foo`

Hope this helps.

Thanks

**Comment by mfreeman-xtivia** [comment]
So I managed to get things working in an AMD-compliant way....
....inside my 'non-AMD' plugin I add one statement at the end like foo_loaded = true; and then use this kind of module spec in the config.js...

~~~~
Loader.addModule({
    dependencies: ['jquery'],
    name: 'foo',
    exports: 'foo_loaded',
    path: MODULE_PATH + '/js/foo.js'
});
~~~~~

and all is right with the world!  :-)

But then of course that begs another question for me....

@ipeychev  @julien  in the scenario above is this module still anonymous from the combo loader's perspective, or does it now know that this module has a name (**foo**) and can thus be loaded ok by the combo loader? 

And put yet another way, what defines whether or not a module is considered anonymous? In the case of a 'real' module that calls define anonymously (i.e. define(['jquery'], func(...)) but has a name property when loaded in config.js, is that module still considered anonymous? or does the use of the 'name' setting in config.js override that?

**Comment by yuchi** [comment]
The short answer is yes, anonymity is related exclusively to the fact that a module is defined with a name or not when `define(...)` is called.

**Comment by ipeychev** [comment]
@mfreeman-xtivia 

> I presume from what I've read that somehow the loader checks the global after parsing the js file and if my exports was set to 'foo' it is going to look for the presence of 'foo' as a variable on the global to know if it succeeded? finished?

Yes, correct

> And does that work for dotted notation? in the case of a jquery plugin that only sets $.fn.foo can I specify 'jQuery.fn.foo' in that exports field and have it work as well?

Yes, it does. It was implemented [here](https://github.com/liferay/liferay-amd-loader/commit/8330b1fe5a66427045ab1761df2ab51af4853a59#diff-e8251939a52be372ecd7aecd39362c6aR383).

@julien @yuchi Correct and thanks for the input.
