### ISSUE TITLE
Package Feature Available?

### ISSUE THREAD

**Issue by mfreeman-xtivia** [liferay/liferay-amd-loader#91]
Does this loader have a feature similar to the 'package' feature provided by require.js? 

Is the initialization code in config.js intended to mimic what one might do with index.js in a package or is that intended to fulfill a totally different need?

thanks

**Comment by ipeychev** [comment]
If you mean [this](http://requirejs.org/docs/api.html#packages), then no, it doesn't.
The code in `config.js` is for other purposes.

**Comment by mfreeman-xtivia** [comment]
@ipeychev thanks

Could you give some typical or comon scenarios/use cases that would then drive one to using the code block in config.js?

**Comment by ipeychev** [comment]
config.js (or any other JS file) is supposed to export a `__CONFIG__` global variable, which contains the configuration of the loader. There you specify modules mapping, paths, the namespace of the loader, etc. You may read the [README](https://github.com/liferay/liferay-amd-loader/blob/master/README.md) for more information.
